INSERT INTO items (item_id, name, unit)
VALUES
(1, 'Ron', 'ml'),
(2, 'Azúcar', 'gr'),
(3, 'Limón', 'unidades'),
(4, 'Hierbabuena', 'ramas'),
(5, 'Piña', 'gramos'),
(6, 'Coco', 'unidades'),
(7, 'Jugo de piña', 'ml'),
(8, 'Tequila', 'ml'),
(9, 'Triple sec', 'ml'),
(10, 'Lima', 'unidades'),
(11, 'Cerveza', 'ml'),
(12, 'Levadura', 'gr'),
(13, 'Malta', 'gr'),
(14, 'Agua', 'ml'),
(15, 'Lúpulo', 'gr'),
(16, 'Cebada', 'gr'),
(17, 'Vainilla', 'ml'),
(18, 'Leche', 'ml'),
(19, 'Crema', 'ml'),
(20, 'Chocolate', 'gr'),
(21, 'Café', 'ml'),
(22, 'Hielo', 'cubos'),
(23, 'Zumo de naranja', 'ml'),
(24, 'Granadina', 'ml'),
(25, 'Cranberry juice', 'ml'),
(26, 'Menta', 'ramas'),
(27, 'Ginebra', 'ml'),
(28, 'Coca-Cola', 'ml'),
(29, 'Pepsi', 'ml'),
(30, 'Fanta', 'ml'),
(31, 'Sprite', 'ml'),
(32, 'Ron Zacapa 23', 'ml'),
(33, 'Whiskey Jack Daniels', 'ml'),
(34, 'Mango', 'gramos'),
(35, 'Fresas', 'gramos');